# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy tatsukonitestfunctionapp1

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  SUBSCRIPTION_ID: "ba29533e-1e4c-43a8-898a-a5815e9b577b"
  NODE_VERSION: "18.x"
  RESOURCE_GROUP_NAME: "tatsukoni-test-v2"
  FUNCTION_NAME: "tatsukonitestfunctionapp1"
  SLOT_NAME: "staging"

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Build
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          popd

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNCTION_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING }}
          respect-funcignore: true

  # swap-production:
  #   needs: build-and-deploy-staging
  #   runs-on: ubuntu-24.04
  #   timeout-minutes: 20
  #   steps:
  #     - name: "Disable Staging Slot Functions except HttpTrigger"
  #       uses: ./.github/actions/disable_staging_functions
  #       with:
  #         service_principal: ${{ secrets.AZURE_CREDENTIALS_FUNCTION_TICKETME_ADMIN_PRD }}
  #         subscription_id: ${{ env.SUBSCRIPTION_ID }}
  #         function_app_name: ${{ env.FUNCTION_NAME }}
  #         resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}

  #     - name: Login via Azure CLI
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS_FUNCTION_TICKETME_PARTNER_PRD }}

  #     - name: Swap Azure Function To Production
  #       id: slot_swap
  #       run: |
  #         az webapp deployment slot swap \
  #           --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
  #           --name ${{ env.FUNCTION_NAME }} \
  #           --slot ${{ env.SLOT_NAME }}

  #     - name: Logout via Azure CLI
  #       run: az logout
